### ISSUE TITLE
Proper error handling?

### ISSUE THREAD

**Issue by Harha** [kutuluk/js13k-2d#1]
Why are all the existing error checks commented out at the moment?

Example: https://github.com/kutuluk/js13k-2d/blob/master/src/renderer.js#L37

If an error occurs with for example OpenGL, I think it should be treated somehow by the lib so that the user of the library can catch it.

**Comment by kutuluk** [comment]
This is done in such a way as to minimize the size of the bundle. Let me remind you that this library is developed primarily for Js13kGames, where the size is very important. During development, error handling can be uncommented. In the future, I will add support for NODE_ENV and I will build two builds for development and production.
