### ISSUE TITLE
Hardcoded OpenGL constants?

### ISSUE THREAD

**Issue by Harha** [kutuluk/js13k-2d#2]
What is the point of using plain integers for representing some if not all of the used OpenGL constants such as GL_TEXTURE_WRAP_S ?

Example: https://github.com/kutuluk/js13k-2d/blob/master/src/renderer.js#L123

I don't know much about WebGL, but if there's a chance that they might not be defined on some weird browsers or something, I think the right thing to do would maybe be to inject the values manually to the gl object in that case?

Using plain integers like that is very confusing.

**Comment by kutuluk** [comment]
This is done in such a way as to minimize the size of the bundle. To avoid confusion, the links to the webgl properties are left in the comments. In all browsers, the values ​​of these constants are the same - they are defined by the standard. The renderer has the `gl` property, which can be used from outside the library to access the required properties.
